// starters/liquid-glass-frontend/apps/web/src/components/ui/kpi-card.tsx
import { type LucideIcon, Minus, TrendingDown, TrendingUp } from "lucide-react"

import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

export type KpiColor =
  | "green"
  | "blue"
  | "red"
  | "purple"
  | "yellow"
  | "default"

export interface KpiCardProps {
  title: string
  value: string | number
  icon?: LucideIcon
  accentColor?: KpiColor
  trend?: {
    value: string | number
    direction: "up" | "down" | "flat"
    label?: string
  }
  className?: string
  loading?: boolean
}

const colorConfig = {
  green: {
    hoverBorder: "hover:border-[var(--lg-primary-border)]",
    blobBg:
      "bg-[var(--lg-primary-dim)]/40 group-hover:bg-[var(--lg-primary-dim)]/80",
    barBg: "bg-[var(--lg-primary)] shadow-[0_0_8px_var(--lg-primary-glow)]",
    trendColor: "text-[var(--lg-primary-light)]",
    iconColor: "text-[var(--lg-primary-light)]",
    iconBg: "bg-[var(--lg-primary-dim)]",
  },
  blue: {
    hoverBorder: "hover:border-[var(--lg-accent-blue-border)]",
    blobBg:
      "bg-[var(--lg-accent-blue-dim)]/40 group-hover:bg-[var(--lg-accent-blue-dim)]/80",
    barBg:
      "bg-[var(--lg-accent-blue)] shadow-[0_0_8px_var(--lg-accent-blue-glow)]",
    trendColor: "text-[var(--lg-accent-blue-light)]",
    iconColor: "text-[var(--lg-accent-blue-light)]",
    iconBg: "bg-[var(--lg-accent-blue-dim)]",
  },
  red: {
    hoverBorder: "hover:border-[var(--lg-accent-red-border)]",
    blobBg:
      "bg-[var(--lg-accent-red-dim)]/40 group-hover:bg-[var(--lg-accent-red-dim)]/80",
    barBg:
      "bg-[var(--lg-accent-red)] shadow-[0_0_8px_var(--lg-accent-red-glow)]",
    trendColor: "text-[var(--lg-accent-red-light)]",
    iconColor: "text-[var(--lg-accent-red-light)]",
    iconBg: "bg-[var(--lg-accent-red-dim)]",
  },
  purple: {
    hoverBorder: "hover:border-[var(--lg-accent-purple-border)]",
    blobBg:
      "bg-[var(--lg-accent-purple-dim)]/40 group-hover:bg-[var(--lg-accent-purple-dim)]/80",
    barBg:
      "bg-[var(--lg-accent-purple)] shadow-[0_0_8px_var(--lg-accent-purple-glow)]",
    trendColor: "text-[var(--lg-accent-purple-light)]",
    iconColor: "text-[var(--lg-accent-purple-light)]",
    iconBg: "bg-[var(--lg-accent-purple-dim)]",
  },
  yellow: {
    hoverBorder: "hover:border-[var(--lg-accent-yellow-border)]",
    blobBg:
      "bg-[var(--lg-accent-yellow-dim)]/40 group-hover:bg-[var(--lg-accent-yellow-dim)]/80",
    barBg:
      "bg-[var(--lg-accent-yellow)] shadow-[0_0_8px_var(--lg-accent-yellow-glow)]",
    trendColor: "text-[var(--lg-accent-yellow-light)]",
    iconColor: "text-[var(--lg-accent-yellow-light)]",
    iconBg: "bg-[var(--lg-accent-yellow-dim)]",
  },
  default: {
    hoverBorder: "hover:border-[var(--lg-border)]",
    blobBg: "bg-transparent",
    barBg: "bg-[var(--lg-border)]",
    trendColor: "text-muted-foreground",
    iconColor: "text-muted-foreground",
    iconBg: "bg-[var(--lg-border-subtle)]",
  },
}

export function KpiCard({
  title,
  value,
  icon: Icon,
  accentColor = "default",
  trend,
  className,
  loading = false,
}: KpiCardProps) {
  const cfg = colorConfig[accentColor] || colorConfig.default

  if (loading) {
    return (
      <Card className="glass-card py-0">
        <CardContent className="p-6">
          <div className="mb-4 flex items-start justify-between">
            <Skeleton className="h-4 w-24" />
            <Skeleton className="size-8 rounded-lg" />
          </div>
          <div className="flex flex-col gap-2">
            <Skeleton className="h-8 w-32" />
            <Skeleton className="h-4 w-40" />
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card
      role="region"
      aria-label={title}
      className={cn(
        "glass-card group relative overflow-hidden py-0 ring-0 transition-all",
        cfg.hoverBorder,
        className
      )}
    >
      <CardContent className="relative z-10 p-6">
        {/* Glow Blob */}
        <div
          className={cn(
            "pointer-events-none absolute top-0 right-0 z-0 -mt-10 -mr-10 h-32 w-32 rounded-full blur-[32px] transition-colors duration-300",
            cfg.blobBg
          )}
        />

        <div className="relative z-10 mb-3 flex items-start justify-between">
          <span className="font-mono text-xs tracking-wider text-muted-foreground uppercase">
            {title}
          </span>
          {Icon && (
            <div
              className={cn("rounded-lg p-1.5 transition-colors", cfg.iconBg)}
            >
              <Icon className={cn("size-4", cfg.iconColor)} />
            </div>
          )}
        </div>

        <div className="relative z-10 flex items-center gap-3">
          <div className={cn("h-8 w-0.5 rounded-sm", cfg.barBg)} />
          <span className="font-data-display leading-none text-foreground">
            {value}
          </span>
        </div>

        {trend && (
          <div
            className={cn(
              "relative z-10 mt-4 flex items-center gap-1 font-mono text-[11px]",
              trend.direction === "up" && "text-emerald-500",
              trend.direction === "down" && "text-red-500",
              trend.direction === "flat" && "text-muted-foreground"
            )}
          >
            {trend.direction === "up" && (
              <TrendingUp className="size-3.5" aria-hidden="true" />
            )}
            {trend.direction === "down" && (
              <TrendingDown className="size-3.5" aria-hidden="true" />
            )}
            {trend.direction === "flat" && (
              <Minus className="size-3.5" aria-hidden="true" />
            )}
            <span>
              {trend.value} {trend.label}
            </span>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// starters/liquid-glass-frontend/src/components/shared/KpiCard.vue
<script setup lang="ts">
/**
 * KpiCard — 通用 KPI 指标卡片
 *
 * 展示单个关键指标，左侧带主色发光竖条。
 * 支持: accentColor (颜色变体)、trend (趋势箭头)、loading 骨架态。
 *
 * 使用示例:
 *   <KpiCard title="总收入" value="$42.5K" :icon="DollarSign" accent-color="green"
 *            :trend="{ value: '+12.5%', direction: 'up', label: 'vs 上月' }" />
 */
import { computed } from 'vue'
import type { Component } from 'vue'
import { TrendingUp, TrendingDown } from 'lucide-vue-next'

const props = withDefaults(defineProps<{
  title: string
  value: string | number
  icon?: Component
  /** 强调色: green | blue | red | purple | yellow */
  accentColor?: 'green' | 'blue' | 'red' | 'purple' | 'yellow'
  trend?: { value: string; direction: 'up' | 'down'; label?: string }
  loading?: boolean
}>(), {
  accentColor: 'green',
  loading: false,
})

const accentVars = computed(() => {
  const prefix = `--lg-accent-${props.accentColor}`
  return {
    '--kpi-accent': `var(${prefix})`,
    '--kpi-accent-dim': `var(${prefix}-dim)`,
    '--kpi-accent-border': `var(${prefix}-border)`,
    '--kpi-accent-glow': `var(${prefix}-glow)`,
  } as Record<string, string>
})
</script>

<template>
  <div
    class="glass-card p-5 relative overflow-hidden"
    :style="{ ...accentVars }"
  >
    <!-- 背景光晕 -->
    <div
      class="absolute -top-8 -right-8 w-24 h-24 rounded-full opacity-20 pointer-events-none"
      :style="{ background: `radial-gradient(circle, var(--kpi-accent-dim), transparent 70%)` }"
    />

    <!-- Loading 骨架 -->
    <template v-if="loading">
      <div class="space-y-3">
        <div class="skeleton-glass h-3 w-16" />
        <div class="skeleton-glass h-7 w-24" />
        <div class="skeleton-glass h-3 w-20" />
      </div>
    </template>

    <template v-else>
      <div class="kpi-accent">
        <!-- 标题行 -->
        <div class="flex items-center gap-2 mb-2">
          <component
            v-if="icon"
            :is="icon"
            class="w-4 h-4"
            style="color: var(--kpi-accent);"
          />
          <p class="data-label" style="color: var(--lg-text-secondary);">{{ title }}</p>
        </div>

        <!-- 数值 -->
        <p class="font-data-display" style="font-size: 28px; color: var(--lg-text-primary);">
          {{ value }}
        </p>

        <!-- 趋势 -->
        <div v-if="trend" class="flex items-center gap-1.5 mt-1.5">
          <TrendingUp
            v-if="trend.direction === 'up'"
            class="w-3.5 h-3.5"
            style="color: var(--lg-primary-light);"
          />
          <TrendingDown
            v-else
            class="w-3.5 h-3.5"
            style="color: var(--lg-accent-red);"
          />
          <span
            class="text-xs font-medium"
            :style="{ color: trend.direction === 'up' ? 'var(--lg-primary-light)' : 'var(--lg-accent-red)' }"
          >
            {{ trend.value }}
          </span>
          <span v-if="trend.label" class="text-xs" style="color: var(--lg-text-muted);">
            {{ trend.label }}
          </span>
        </div>
      </div>
    </template>
  </div>
</template>
